### ISSUE TITLE
No element "alsasrc"

### ISSUE THREAD

**Issue by danlamanna** [arrdem/Voicely#1]
Hey guys - first off thanks for creating this library, this seems like it will be much easier to use than the rest of what I've researched.

Anyway - when running `voicely -dbg` I receive the following Traceback:
https://gist.github.com/danlamanna/5221502

Removing the beginning `alsasrc !` from the parse_launch argument does stop the error, but voicely itself doesn't respond to commands then, so I'm assuming the alsasrc bit may have been the issue.

I'm using the built in conf provided (minus the keyphrase, and having use_keyphrase set to 0).

Running Arch (Linux Kernel 3.8.4-1) - Let me know if there are any other details I can give.

Thanks!

**Comment by danlamanna** [comment]
I actually just fixed this by installing all gstreamer-plugins, sorry!

**Comment by arrdem** [comment]
No worries, I admit that I never made an effort to properly enumerate dependencies for Voicely. I hope you find it useful, if not please complain as Voicely is one of those projects that I put down when it was badly in need of a cleanup.
